import { Basket } from "./domains/Basket";
import { Pant } from "./domains/Pant";
import { BasketManagerDinamic } from "./services/BasketManagerDinamic";
import { currencies } from "./utils/constants";
import { allClothesNames } from "./utils/constants";
import { brands } from "./utils/constants";
import { sizes } from "./utils/constants";
import { colors } from "./utils/constants";
import { materials } from "./utils/constants";
import { genders } from "./utils/constants";
import { fits } from "./utils/constants";
import { pocketCounts } from "./utils/constants";
import { Hoodie } from "./domains/Hoodie";
import { Tshirt } from "./domains/Tshirt";
import { Sneakers } from "./domains/Sneakers";
import { designTypes } from "./utils/constants";
import { closureTypes } from "./utils/constants";
import { hoodTypes } from "./utils/constants";
import { sleeveLengths } from "./utils/constants";
import { Jacket } from "./domains/Jacket";

const basket = new Basket();
const basketManager = new BasketManagerDinamic(basket, currencies.EURO);
